### ISSUE TITLE
gulp-filter is not letting any files pass.

### ISSUE THREAD

**Issue by mnbroatch** [sindresorhus/gulp-filter#71]
Hi, I'm new to the plugin but this definitely seems like a bug.

gulp.task('js', function(cb){
	const jsFiles = ['./client/js/**/*.js'];
	pump([	
		gulp.src(jsFiles),
		filter('*.js'),
		concat('main.js'),
		babel({
			presets:['es2015']
		}).on('error', gutil.log),
		uglify(),
		gulp.dest(dest + 'js')
	],
	cb
	);
});

The problem is that no files are passing through the filter. When I take the filter out, my .js files are processed correctly.

**Comment by Martinsos** [comment]
@mnbroatch: I also had similar problem, and this seems to be caused by the [issue in minimatch](https://github.com/isaacs/minimatch/issues/30), which propagates to gulp-filter.

In my case, filepaths contained a dot, and that was the reason they were filtered out (because that is what gulp-filter does by default). So try using filter as `filter('*.js', {dot: true})` and see if that helps.

**Comment by akullpp** [comment]
Fixed by using the option `dot: true`

**Comment by sindresorhus** [comment]
Support questions are better asked on Stack Overflow:
http://stackoverflow.com/questions/tagged/gulp
Paste in the link to the question here so others can follow ;)
